spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: incident-monitoring
  
  datasource:
    url: jdbc:***REMOVED***ql://localhost:5432/***REMOVED***
    username: omarfofana
    password: ***REMOVED***
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: ${JWT_SECRET}